---
ansible_user: "{{ vault_ansible_user }}"
monitor_user: "{{ vault_monitor_user }}"
meshtastic_host: "{{ vault_meshtastic_host }}"

# UPS logging configuration
ups_log_interval: 60

# UPS load correction factor
ups_power_multiplier: 18

# Mesh alert behavior
ups_mesh_restore_delay: 300
ups_mesh_low_voltage: 10.2
ups_mesh_shutdown_voltage: 9.8
