## OPTIONS ARE TCP or SERIAL
meshtastic_connection: serial

## FOR TCP CONNECTIONS
#meshtastic_host: NODE_IP
#meshtastic_port: unused

## VARIOUS SERIAL CONNECTIONS
#meshtastic_port: /dev/ttyUSB0
#meshtastic_port: /dev/serial0
meshtastic_port: /dev/ttyACM0


## Monitored node information
local_node_id: "!49b44a44"
